name: verify
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: pip3 install -U online-judge-verify-helper
      - name: Run tests
        run: oj-verify all --jobs 2 --tle 20 --timeout 3600
