name: verify-and-deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pages: write
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip3 install -U online-judge-verify-helper
      - name: Run tests
        run: oj-verify all --jobs 2 --tle 20 --timeout 3600
      - name: Push markdown to branch "gh-pages"
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          cp -a .verify-helper/markdown/. .
          git add -A
          git commit -m "deploy docs (run ${GITHUB_RUN_ID})"
          git push -u origin gh-pages --force
